services:
  mongo:
    image: mongo:7.0
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - ricoz-data:/data/db
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mongosh --quiet --eval "try { rs.status().ok } catch (e) { rs.initiate({_id:''rs0'',members:[{_id:0,host:''localhost:27017''}]}).ok }"',
        ]
      interval: 5s
      timeout: 10s
      retries: 20
volumes:
  ricoz-data:
